apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  name: flights-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: flightsservice
          servicePort: 9000
        path: /flights
  tls:
  - secretName: flights-tls-secret